import { createClient } from 'npm:@supabase/supabase-js@2';
import { corsHeaders } from 'npm:@supabase/supabase-js@2/cors';
export { corsHeaders };
export const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), {status, headers:{...corsHeaders,'Content-Type':'application/json'}});
export function db() { const url=Deno.env.get('SUPABASE_URL'), key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'); if(!url || !key) throw new Error('Service unavailable'); return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}); }
export type Meta = {hash?:string; telegram_status:string; payment_status:string; steps:Record<string,number>; attempts:number; error?:string; updated_at?:string};
export async function readMeta(client:any,id:string):Promise<Meta> { const {data}=await client.storage.from('registration-internal').download(`records/${id}.json`); return data ? JSON.parse(await data.text()) : {telegram_status:'unknown',payment_status:'pending',steps:{},attempts:0}; }
export async function writeMeta(client:any,id:string,meta:Meta) { const {error}=await client.storage.from('registration-internal').upload(`records/${id}.json`,new Blob([JSON.stringify({...meta,updated_at:new Date().toISOString()})],{type:'application/json'}),{upsert:true}); if(error) throw new Error('Delivery tracking unavailable'); }
export async function admin(pin:unknown) { const expected=Deno.env.get('ADMIN_PIN'); if(typeof pin!=='string'||!expected||pin.length!==expected.length) return false; const a=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(pin)),b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(expected)); return new Uint8Array(a).every((v,i)=>v===new Uint8Array(b)[i]); }
export async function media(client:any,ref:string) { let bucket='mpl-player-media',path=ref; if(ref.startsWith('http')) { const url=new URL(ref); const configured=new URL(Deno.env.get('SUPABASE_URL')||''); if(url.host!==configured.host) throw new Error('Unrecognized stored file'); const match=url.pathname.match(/\/storage\/v1\/object\/(?:sign|public)\/player-files\/(.+)/); if(!match) throw new Error('Invalid file reference'); bucket='player-files'; path=decodeURIComponent(match[1]); } else if(!/^(profile-photos|payment-screenshots)\/[a-f0-9-]+\.(jpg|png)$/.test(path)) throw new Error('Invalid file reference'); const {data,error}=await client.storage.from(bucket).download(path); if(error||!data) throw new Error('Stored image unavailable'); if(data.size>5*1024*1024||!['image/jpeg','image/png'].includes(data.type)) throw new Error('Invalid stored image'); return data as Blob; }
export async function signed(client:any,ref:string|null) { if(!ref) return null; let bucket='mpl-player-media',path=ref; if(ref.startsWith('http')) { const match=new URL(ref).pathname.match(/\/storage\/v1\/object\/(?:sign|public)\/player-files\/(.+)/); if(!match) return null; bucket='player-files';path=decodeURIComponent(match[1]); } const {data}=await client.storage.from(bucket).createSignedUrl(path,3600); return data?.signedUrl||null; }
async function telegram(method:string,body:()=>BodyInit, multipart=false) { const token=Deno.env.get('TELEGRAM_BOT_TOKEN'); if(!token) throw new Error('Telegram bot is not configured'); for(let attempt=0;attempt<3;attempt++) { try { const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:multipart?undefined:{'Content-Type':'application/json'},body:body(),signal:AbortSignal.timeout(12000)}); const data=await r.json(); if(r.ok&&data.ok) return data.result; const retryable=r.status===429||r.status>=500; if(!retryable||attempt===2) throw Object.assign(new Error(`Telegram ${method} failed (${r.status}): ${String(data.description||'request rejected').slice(0,200)}`),{terminal:true}); const delay=Math.min(10000,Math.max(1000*2**attempt,(data.parameters?.retry_after||0)*1000)); await new Promise(r=>setTimeout(r,delay)); } catch(e) { if((e as any).terminal||attempt===2) throw e; await new Promise(r=>setTimeout(r,1000*2**attempt)); } } throw new Error('Telegram delivery failed'); }
export async function deliver(client:any,player:any,meta:Meta) { if(meta.telegram_status==='delivered') return meta; const lock=`delivery/${player.id}.lock`; const {error:locked}=await client.storage.from('registration-internal').upload(lock,new Blob(['processing']),{upsert:false}); if(locked) return {...meta,telegram_status:'pending'}; try { meta.telegram_status='pending';meta.attempts++;await writeMeta(client,player.id,meta); const {data:target}=await client.storage.from('registration-internal').download('telegram-target.json'); const chat=Deno.env.get('TELEGRAM_CHAT_ID')||(target?JSON.parse(await target.text()).chat_id:null); if(!chat) throw new Error('Organizer must configure the Telegram destination'); const blobs=await Promise.all([media(client,player.profile_photo_url),media(client,player.resume_url)]);
 const hidden=new Set(['id','user_id','profile_photo_url','resume_url','gov_id_url']); const lines=Object.entries(player).filter(([k,v])=>!hidden.has(k)&&v!==null&&v!=='').map(([k,v])=>`${k.replace(/_/g,' ').replace(/^./,s=>s.toUpperCase())}: ${v}`); const text=['🏏 MPL 2026 — NEW PLAYER REGISTRATION',...lines,`Payment: ${meta.payment_status.replace(/_/g,' ')}`,'Player photo and payment proof: attached below'].join('\n'); const chunks=text.match(/[\s\S]{1,3900}/g)||[];
 for(let i=0;i<chunks.length;i++) {const key=`text_${i}`;if(!meta.steps[key]) { const msg=await telegram('sendMessage',()=>JSON.stringify({chat_id:chat,text:chunks[i]}));meta.steps[key]=msg.message_id;await writeMeta(client,player.id,meta);}}
 for(let i=0;i<blobs.length;i++){const key=i===0?'profile_photo':'payment_proof';if(meta.steps[key])continue;const build=(field:string)=>{const f=new FormData();f.set('chat_id',String(chat));f.set('caption',`${i===0?'PLAYER PHOTO':'PAYMENT SCREENSHOT'} • ${player.full_name} • ${player.registration_id}`);f.set(field,blobs[i],`${key}.${blobs[i].type==='image/png'?'png':'jpg'}`);return f;};let msg;try{msg=await telegram('sendPhoto',()=>build('photo'),true);}catch(e){if(!(e as any).terminal)throw e;msg=await telegram('sendDocument',()=>build('document'),true);}meta.steps[key]=msg.message_id;await writeMeta(client,player.id,meta);}
 meta.telegram_status='delivered';delete meta.error;await writeMeta(client,player.id,meta);return meta;
 }catch(e){meta.telegram_status='failed';meta.error=e instanceof Error?e.message:'Delivery failed';console.error('MPL delivery failed',player.registration_id,meta.error);await writeMeta(client,player.id,meta);return meta;}finally{await client.storage.from('registration-internal').remove([lock]);} }
