import {useState,useRef,useEffect} from 'react';
import {Upload,Loader2,X,RefreshCw,CheckCircle} from 'lucide-react';
import {supabase} from '@/integrations/supabase/client';
import {Button} from './button';
interface Props {folder:'profile-photos'|'payment-screenshots'|'government-ids'|'resumes'|'medical-certs';accept:string;maxSizeMB:number;label:string;required?:boolean;value?:string;disabled?:boolean;onUploadComplete?:(path:string)=>void;onUploadingChange?:(busy:boolean)=>void;}
export default function FileUpload({folder,accept,maxSizeMB,label,required,value='',disabled=false,onUploadComplete,onUploadingChange}:Props){const [uploading,setUploading]=useState(false),[preview,setPreview]=useState(''),[error,setError]=useState('');const input=useRef<HTMLInputElement>(null);useEffect(()=>{if(!value)setPreview('');else if(value.startsWith('http'))setPreview(value);},[value]);
const select=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setError('');if(!['image/jpeg','image/png'].includes(file.type)){setError('Choose a JPG, JPEG or PNG image.');return;}if(!file.size||file.size>maxSizeMB*1024*1024){setError(`Choose an image up to ${maxSizeMB} MB.`);return;}setUploading(true);onUploadingChange?.(true);try{const form=new FormData();form.set('file',file);form.set('folder',folder);const {data,error}=await supabase.functions.invoke('upload-player-media',{body:form});if(error||!data?.path)throw new Error();setPreview(data.preview_url);onUploadComplete?.(data.path);}catch{setError('Upload failed. Please check your connection and try again.');}finally{setUploading(false);onUploadingChange?.(false);if(input.current)input.current.value='';}};
return <div className="space-y-3"><input ref={input} type="file" accept={accept} aria-label={label} onChange={select} className="sr-only" disabled={uploading||disabled}/>{preview?<div className="rounded-lg border border-border p-3"><img src={preview} alt={`${label} preview`} className="mx-auto max-h-56 w-full object-contain"/><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><span className="flex items-center gap-2 text-xs text-accent"><CheckCircle className="h-4 w-4"/> {uploading?'Uploading replacement…':'Image uploaded'}</span><div className="flex gap-1"><Button variant="outline" type="button" disabled={uploading||disabled} onClick={()=>input.current?.click()} aria-label={`Replace ${label}`}><RefreshCw/>Replace</Button><Button variant="ghost" type="button" disabled={uploading||disabled} aria-label={`Remove ${label}`} onClick={()=>{setPreview('');onUploadComplete?.('');}}><X/></Button></div></div></div>:<Button type="button" variant="outline" className="h-auto w-full flex-col gap-2 border-dashed py-7" disabled={uploading||disabled} onClick={()=>input.current?.click()}>{uploading?<Loader2 className="h-6 w-6 animate-spin"/>:<Upload className="h-6 w-6 text-accent"/>}<span>{uploading?'Uploading image…':`Upload ${label}${required?' *':''}`}</span><span className="text-xs font-normal text-muted-foreground">JPG / PNG · Up to {maxSizeMB} MB</span></Button>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}</div>;
}
